/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as AuthenticatedHomeLayoutImport } from './routes/_authenticated/_home-layout'
import { Route as AuthRegisterIndexImport } from './routes/auth/register/index'
import { Route as AuthLoginIndexImport } from './routes/auth/login/index'
import { Route as AuthenticatedHomeLayoutIndexImport } from './routes/_authenticated/_home-layout/index'
import { Route as AuthenticatedOffersCreateIndexImport } from './routes/_authenticated/offers/create.index'
import { Route as AuthenticatedJobsCreateIndexImport } from './routes/_authenticated/jobs/create.index'
import { Route as AuthenticatedChatsConversationIndexImport } from './routes/_authenticated/chats/conversation/index'
import { Route as AuthenticatedHomeLayoutOffersIndexImport } from './routes/_authenticated/_home-layout/offers.index'
import { Route as AuthenticatedHomeLayoutJobsIndexImport } from './routes/_authenticated/_home-layout/jobs.index'
import { Route as AuthenticatedHomeLayoutChatsIndexImport } from './routes/_authenticated/_home-layout/chats.index'
import { Route as AuthenticatedHomeLayoutAccountIndexImport } from './routes/_authenticated/_home-layout/account.index'
import { Route as AuthenticatedJobsDetailJobIdIndexImport } from './routes/_authenticated/jobs/detail.$jobId.index'

// Create/Update Routes

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedHomeLayoutRoute = AuthenticatedHomeLayoutImport.update({
  id: '/_home-layout',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthRegisterIndexRoute = AuthRegisterIndexImport.update({
  id: '/auth/register/',
  path: '/auth/register/',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginIndexRoute = AuthLoginIndexImport.update({
  id: '/auth/login/',
  path: '/auth/login/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedHomeLayoutIndexRoute =
  AuthenticatedHomeLayoutIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedHomeLayoutRoute,
  } as any)

const AuthenticatedOffersCreateIndexRoute =
  AuthenticatedOffersCreateIndexImport.update({
    id: '/offers/create/',
    path: '/offers/create/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedJobsCreateIndexRoute =
  AuthenticatedJobsCreateIndexImport.update({
    id: '/jobs/create/',
    path: '/jobs/create/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedChatsConversationIndexRoute =
  AuthenticatedChatsConversationIndexImport.update({
    id: '/chats/conversation/',
    path: '/chats/conversation/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedHomeLayoutOffersIndexRoute =
  AuthenticatedHomeLayoutOffersIndexImport.update({
    id: '/offers/',
    path: '/offers/',
    getParentRoute: () => AuthenticatedHomeLayoutRoute,
  } as any)

const AuthenticatedHomeLayoutJobsIndexRoute =
  AuthenticatedHomeLayoutJobsIndexImport.update({
    id: '/jobs/',
    path: '/jobs/',
    getParentRoute: () => AuthenticatedHomeLayoutRoute,
  } as any)

const AuthenticatedHomeLayoutChatsIndexRoute =
  AuthenticatedHomeLayoutChatsIndexImport.update({
    id: '/chats/',
    path: '/chats/',
    getParentRoute: () => AuthenticatedHomeLayoutRoute,
  } as any)

const AuthenticatedHomeLayoutAccountIndexRoute =
  AuthenticatedHomeLayoutAccountIndexImport.update({
    id: '/account/',
    path: '/account/',
    getParentRoute: () => AuthenticatedHomeLayoutRoute,
  } as any)

const AuthenticatedJobsDetailJobIdIndexRoute =
  AuthenticatedJobsDetailJobIdIndexImport.update({
    id: '/jobs/detail/$jobId/',
    path: '/jobs/detail/$jobId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/_home-layout': {
      id: '/_authenticated/_home-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedHomeLayoutImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/_home-layout/': {
      id: '/_authenticated/_home-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedHomeLayoutIndexImport
      parentRoute: typeof AuthenticatedHomeLayoutImport
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/register/': {
      id: '/auth/register/'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterIndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/_home-layout/account/': {
      id: '/_authenticated/_home-layout/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedHomeLayoutAccountIndexImport
      parentRoute: typeof AuthenticatedHomeLayoutImport
    }
    '/_authenticated/_home-layout/chats/': {
      id: '/_authenticated/_home-layout/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedHomeLayoutChatsIndexImport
      parentRoute: typeof AuthenticatedHomeLayoutImport
    }
    '/_authenticated/_home-layout/jobs/': {
      id: '/_authenticated/_home-layout/jobs/'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AuthenticatedHomeLayoutJobsIndexImport
      parentRoute: typeof AuthenticatedHomeLayoutImport
    }
    '/_authenticated/_home-layout/offers/': {
      id: '/_authenticated/_home-layout/offers/'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof AuthenticatedHomeLayoutOffersIndexImport
      parentRoute: typeof AuthenticatedHomeLayoutImport
    }
    '/_authenticated/chats/conversation/': {
      id: '/_authenticated/chats/conversation/'
      path: '/chats/conversation'
      fullPath: '/chats/conversation'
      preLoaderRoute: typeof AuthenticatedChatsConversationIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/jobs/create/': {
      id: '/_authenticated/jobs/create/'
      path: '/jobs/create'
      fullPath: '/jobs/create'
      preLoaderRoute: typeof AuthenticatedJobsCreateIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/offers/create/': {
      id: '/_authenticated/offers/create/'
      path: '/offers/create'
      fullPath: '/offers/create'
      preLoaderRoute: typeof AuthenticatedOffersCreateIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/jobs/detail/$jobId/': {
      id: '/_authenticated/jobs/detail/$jobId/'
      path: '/jobs/detail/$jobId'
      fullPath: '/jobs/detail/$jobId'
      preLoaderRoute: typeof AuthenticatedJobsDetailJobIdIndexImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedHomeLayoutRouteChildren {
  AuthenticatedHomeLayoutIndexRoute: typeof AuthenticatedHomeLayoutIndexRoute
  AuthenticatedHomeLayoutAccountIndexRoute: typeof AuthenticatedHomeLayoutAccountIndexRoute
  AuthenticatedHomeLayoutChatsIndexRoute: typeof AuthenticatedHomeLayoutChatsIndexRoute
  AuthenticatedHomeLayoutJobsIndexRoute: typeof AuthenticatedHomeLayoutJobsIndexRoute
  AuthenticatedHomeLayoutOffersIndexRoute: typeof AuthenticatedHomeLayoutOffersIndexRoute
}

const AuthenticatedHomeLayoutRouteChildren: AuthenticatedHomeLayoutRouteChildren =
  {
    AuthenticatedHomeLayoutIndexRoute: AuthenticatedHomeLayoutIndexRoute,
    AuthenticatedHomeLayoutAccountIndexRoute:
      AuthenticatedHomeLayoutAccountIndexRoute,
    AuthenticatedHomeLayoutChatsIndexRoute:
      AuthenticatedHomeLayoutChatsIndexRoute,
    AuthenticatedHomeLayoutJobsIndexRoute:
      AuthenticatedHomeLayoutJobsIndexRoute,
    AuthenticatedHomeLayoutOffersIndexRoute:
      AuthenticatedHomeLayoutOffersIndexRoute,
  }

const AuthenticatedHomeLayoutRouteWithChildren =
  AuthenticatedHomeLayoutRoute._addFileChildren(
    AuthenticatedHomeLayoutRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedHomeLayoutRoute: typeof AuthenticatedHomeLayoutRouteWithChildren
  AuthenticatedChatsConversationIndexRoute: typeof AuthenticatedChatsConversationIndexRoute
  AuthenticatedJobsCreateIndexRoute: typeof AuthenticatedJobsCreateIndexRoute
  AuthenticatedOffersCreateIndexRoute: typeof AuthenticatedOffersCreateIndexRoute
  AuthenticatedJobsDetailJobIdIndexRoute: typeof AuthenticatedJobsDetailJobIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedHomeLayoutRoute: AuthenticatedHomeLayoutRouteWithChildren,
  AuthenticatedChatsConversationIndexRoute:
    AuthenticatedChatsConversationIndexRoute,
  AuthenticatedJobsCreateIndexRoute: AuthenticatedJobsCreateIndexRoute,
  AuthenticatedOffersCreateIndexRoute: AuthenticatedOffersCreateIndexRoute,
  AuthenticatedJobsDetailJobIdIndexRoute:
    AuthenticatedJobsDetailJobIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof AuthenticatedHomeLayoutRouteWithChildren
  '/': typeof AuthenticatedHomeLayoutIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/register': typeof AuthRegisterIndexRoute
  '/account': typeof AuthenticatedHomeLayoutAccountIndexRoute
  '/chats': typeof AuthenticatedHomeLayoutChatsIndexRoute
  '/jobs': typeof AuthenticatedHomeLayoutJobsIndexRoute
  '/offers': typeof AuthenticatedHomeLayoutOffersIndexRoute
  '/chats/conversation': typeof AuthenticatedChatsConversationIndexRoute
  '/jobs/create': typeof AuthenticatedJobsCreateIndexRoute
  '/offers/create': typeof AuthenticatedOffersCreateIndexRoute
  '/jobs/detail/$jobId': typeof AuthenticatedJobsDetailJobIdIndexRoute
}

export interface FileRoutesByTo {
  '': typeof AuthenticatedRouteWithChildren
  '/': typeof AuthenticatedHomeLayoutIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/register': typeof AuthRegisterIndexRoute
  '/account': typeof AuthenticatedHomeLayoutAccountIndexRoute
  '/chats': typeof AuthenticatedHomeLayoutChatsIndexRoute
  '/jobs': typeof AuthenticatedHomeLayoutJobsIndexRoute
  '/offers': typeof AuthenticatedHomeLayoutOffersIndexRoute
  '/chats/conversation': typeof AuthenticatedChatsConversationIndexRoute
  '/jobs/create': typeof AuthenticatedJobsCreateIndexRoute
  '/offers/create': typeof AuthenticatedOffersCreateIndexRoute
  '/jobs/detail/$jobId': typeof AuthenticatedJobsDetailJobIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/_home-layout': typeof AuthenticatedHomeLayoutRouteWithChildren
  '/_authenticated/_home-layout/': typeof AuthenticatedHomeLayoutIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/register/': typeof AuthRegisterIndexRoute
  '/_authenticated/_home-layout/account/': typeof AuthenticatedHomeLayoutAccountIndexRoute
  '/_authenticated/_home-layout/chats/': typeof AuthenticatedHomeLayoutChatsIndexRoute
  '/_authenticated/_home-layout/jobs/': typeof AuthenticatedHomeLayoutJobsIndexRoute
  '/_authenticated/_home-layout/offers/': typeof AuthenticatedHomeLayoutOffersIndexRoute
  '/_authenticated/chats/conversation/': typeof AuthenticatedChatsConversationIndexRoute
  '/_authenticated/jobs/create/': typeof AuthenticatedJobsCreateIndexRoute
  '/_authenticated/offers/create/': typeof AuthenticatedOffersCreateIndexRoute
  '/_authenticated/jobs/detail/$jobId/': typeof AuthenticatedJobsDetailJobIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/account'
    | '/chats'
    | '/jobs'
    | '/offers'
    | '/chats/conversation'
    | '/jobs/create'
    | '/offers/create'
    | '/jobs/detail/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/account'
    | '/chats'
    | '/jobs'
    | '/offers'
    | '/chats/conversation'
    | '/jobs/create'
    | '/offers/create'
    | '/jobs/detail/$jobId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/_home-layout'
    | '/_authenticated/_home-layout/'
    | '/auth/login/'
    | '/auth/register/'
    | '/_authenticated/_home-layout/account/'
    | '/_authenticated/_home-layout/chats/'
    | '/_authenticated/_home-layout/jobs/'
    | '/_authenticated/_home-layout/offers/'
    | '/_authenticated/chats/conversation/'
    | '/_authenticated/jobs/create/'
    | '/_authenticated/offers/create/'
    | '/_authenticated/jobs/detail/$jobId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/auth/login/",
        "/auth/register/"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/_home-layout",
        "/_authenticated/chats/conversation/",
        "/_authenticated/jobs/create/",
        "/_authenticated/offers/create/",
        "/_authenticated/jobs/detail/$jobId/"
      ]
    },
    "/_authenticated/_home-layout": {
      "filePath": "_authenticated/_home-layout.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/_home-layout/",
        "/_authenticated/_home-layout/account/",
        "/_authenticated/_home-layout/chats/",
        "/_authenticated/_home-layout/jobs/",
        "/_authenticated/_home-layout/offers/"
      ]
    },
    "/_authenticated/_home-layout/": {
      "filePath": "_authenticated/_home-layout/index.tsx",
      "parent": "/_authenticated/_home-layout"
    },
    "/auth/login/": {
      "filePath": "auth/login/index.tsx"
    },
    "/auth/register/": {
      "filePath": "auth/register/index.tsx"
    },
    "/_authenticated/_home-layout/account/": {
      "filePath": "_authenticated/_home-layout/account.index.tsx",
      "parent": "/_authenticated/_home-layout"
    },
    "/_authenticated/_home-layout/chats/": {
      "filePath": "_authenticated/_home-layout/chats.index.tsx",
      "parent": "/_authenticated/_home-layout"
    },
    "/_authenticated/_home-layout/jobs/": {
      "filePath": "_authenticated/_home-layout/jobs.index.tsx",
      "parent": "/_authenticated/_home-layout"
    },
    "/_authenticated/_home-layout/offers/": {
      "filePath": "_authenticated/_home-layout/offers.index.tsx",
      "parent": "/_authenticated/_home-layout"
    },
    "/_authenticated/chats/conversation/": {
      "filePath": "_authenticated/chats/conversation/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/jobs/create/": {
      "filePath": "_authenticated/jobs/create.index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/offers/create/": {
      "filePath": "_authenticated/offers/create.index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/jobs/detail/$jobId/": {
      "filePath": "_authenticated/jobs/detail.$jobId.index.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
