/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as AuthenticatedHomeLayoutImport } from './routes/_authenticated/_home-layout'
import { Route as AuthRegisterIndexImport } from './routes/auth/register/index'
import { Route as AuthLoginIndexImport } from './routes/auth/login/index'
import { Route as AuthenticatedHomeLayoutIndexImport } from './routes/_authenticated/_home-layout/index'
import { Route as AuthenticatedHomeLayoutOffersImport } from './routes/_authenticated/_home-layout/offers'
import { Route as AuthenticatedHomeLayoutJobsImport } from './routes/_authenticated/_home-layout/jobs'
import { Route as AuthenticatedHomeLayoutChatsImport } from './routes/_authenticated/_home-layout/chats'
import { Route as AuthenticatedHomeLayoutAccountImport } from './routes/_authenticated/_home-layout/account'
import { Route as AuthenticatedOffersCreateIndexImport } from './routes/_authenticated/offers/create/index'
import { Route as AuthenticatedJobsCreateIndexImport } from './routes/_authenticated/jobs/create/index'
import { Route as AuthenticatedChatsConversationIndexImport } from './routes/_authenticated/chats/conversation/index'

// Create/Update Routes

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedHomeLayoutRoute = AuthenticatedHomeLayoutImport.update({
  id: '/_home-layout',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthRegisterIndexRoute = AuthRegisterIndexImport.update({
  id: '/auth/register/',
  path: '/auth/register/',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginIndexRoute = AuthLoginIndexImport.update({
  id: '/auth/login/',
  path: '/auth/login/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedHomeLayoutIndexRoute =
  AuthenticatedHomeLayoutIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedHomeLayoutRoute,
  } as any)

const AuthenticatedHomeLayoutOffersRoute =
  AuthenticatedHomeLayoutOffersImport.update({
    id: '/offers',
    path: '/offers',
    getParentRoute: () => AuthenticatedHomeLayoutRoute,
  } as any)

const AuthenticatedHomeLayoutJobsRoute =
  AuthenticatedHomeLayoutJobsImport.update({
    id: '/jobs',
    path: '/jobs',
    getParentRoute: () => AuthenticatedHomeLayoutRoute,
  } as any)

const AuthenticatedHomeLayoutChatsRoute =
  AuthenticatedHomeLayoutChatsImport.update({
    id: '/chats',
    path: '/chats',
    getParentRoute: () => AuthenticatedHomeLayoutRoute,
  } as any)

const AuthenticatedHomeLayoutAccountRoute =
  AuthenticatedHomeLayoutAccountImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedHomeLayoutRoute,
  } as any)

const AuthenticatedOffersCreateIndexRoute =
  AuthenticatedOffersCreateIndexImport.update({
    id: '/offers/create/',
    path: '/offers/create/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedJobsCreateIndexRoute =
  AuthenticatedJobsCreateIndexImport.update({
    id: '/jobs/create/',
    path: '/jobs/create/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedChatsConversationIndexRoute =
  AuthenticatedChatsConversationIndexImport.update({
    id: '/chats/conversation/',
    path: '/chats/conversation/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/_home-layout': {
      id: '/_authenticated/_home-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedHomeLayoutImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/_home-layout/account': {
      id: '/_authenticated/_home-layout/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedHomeLayoutAccountImport
      parentRoute: typeof AuthenticatedHomeLayoutImport
    }
    '/_authenticated/_home-layout/chats': {
      id: '/_authenticated/_home-layout/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedHomeLayoutChatsImport
      parentRoute: typeof AuthenticatedHomeLayoutImport
    }
    '/_authenticated/_home-layout/jobs': {
      id: '/_authenticated/_home-layout/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AuthenticatedHomeLayoutJobsImport
      parentRoute: typeof AuthenticatedHomeLayoutImport
    }
    '/_authenticated/_home-layout/offers': {
      id: '/_authenticated/_home-layout/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof AuthenticatedHomeLayoutOffersImport
      parentRoute: typeof AuthenticatedHomeLayoutImport
    }
    '/_authenticated/_home-layout/': {
      id: '/_authenticated/_home-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedHomeLayoutIndexImport
      parentRoute: typeof AuthenticatedHomeLayoutImport
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/register/': {
      id: '/auth/register/'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterIndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/chats/conversation/': {
      id: '/_authenticated/chats/conversation/'
      path: '/chats/conversation'
      fullPath: '/chats/conversation'
      preLoaderRoute: typeof AuthenticatedChatsConversationIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/jobs/create/': {
      id: '/_authenticated/jobs/create/'
      path: '/jobs/create'
      fullPath: '/jobs/create'
      preLoaderRoute: typeof AuthenticatedJobsCreateIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/offers/create/': {
      id: '/_authenticated/offers/create/'
      path: '/offers/create'
      fullPath: '/offers/create'
      preLoaderRoute: typeof AuthenticatedOffersCreateIndexImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedHomeLayoutRouteChildren {
  AuthenticatedHomeLayoutAccountRoute: typeof AuthenticatedHomeLayoutAccountRoute
  AuthenticatedHomeLayoutChatsRoute: typeof AuthenticatedHomeLayoutChatsRoute
  AuthenticatedHomeLayoutJobsRoute: typeof AuthenticatedHomeLayoutJobsRoute
  AuthenticatedHomeLayoutOffersRoute: typeof AuthenticatedHomeLayoutOffersRoute
  AuthenticatedHomeLayoutIndexRoute: typeof AuthenticatedHomeLayoutIndexRoute
}

const AuthenticatedHomeLayoutRouteChildren: AuthenticatedHomeLayoutRouteChildren =
  {
    AuthenticatedHomeLayoutAccountRoute: AuthenticatedHomeLayoutAccountRoute,
    AuthenticatedHomeLayoutChatsRoute: AuthenticatedHomeLayoutChatsRoute,
    AuthenticatedHomeLayoutJobsRoute: AuthenticatedHomeLayoutJobsRoute,
    AuthenticatedHomeLayoutOffersRoute: AuthenticatedHomeLayoutOffersRoute,
    AuthenticatedHomeLayoutIndexRoute: AuthenticatedHomeLayoutIndexRoute,
  }

const AuthenticatedHomeLayoutRouteWithChildren =
  AuthenticatedHomeLayoutRoute._addFileChildren(
    AuthenticatedHomeLayoutRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedHomeLayoutRoute: typeof AuthenticatedHomeLayoutRouteWithChildren
  AuthenticatedChatsConversationIndexRoute: typeof AuthenticatedChatsConversationIndexRoute
  AuthenticatedJobsCreateIndexRoute: typeof AuthenticatedJobsCreateIndexRoute
  AuthenticatedOffersCreateIndexRoute: typeof AuthenticatedOffersCreateIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedHomeLayoutRoute: AuthenticatedHomeLayoutRouteWithChildren,
  AuthenticatedChatsConversationIndexRoute:
    AuthenticatedChatsConversationIndexRoute,
  AuthenticatedJobsCreateIndexRoute: AuthenticatedJobsCreateIndexRoute,
  AuthenticatedOffersCreateIndexRoute: AuthenticatedOffersCreateIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof AuthenticatedHomeLayoutRouteWithChildren
  '/account': typeof AuthenticatedHomeLayoutAccountRoute
  '/chats': typeof AuthenticatedHomeLayoutChatsRoute
  '/jobs': typeof AuthenticatedHomeLayoutJobsRoute
  '/offers': typeof AuthenticatedHomeLayoutOffersRoute
  '/': typeof AuthenticatedHomeLayoutIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/register': typeof AuthRegisterIndexRoute
  '/chats/conversation': typeof AuthenticatedChatsConversationIndexRoute
  '/jobs/create': typeof AuthenticatedJobsCreateIndexRoute
  '/offers/create': typeof AuthenticatedOffersCreateIndexRoute
}

export interface FileRoutesByTo {
  '': typeof AuthenticatedRouteWithChildren
  '/account': typeof AuthenticatedHomeLayoutAccountRoute
  '/chats': typeof AuthenticatedHomeLayoutChatsRoute
  '/jobs': typeof AuthenticatedHomeLayoutJobsRoute
  '/offers': typeof AuthenticatedHomeLayoutOffersRoute
  '/': typeof AuthenticatedHomeLayoutIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/register': typeof AuthRegisterIndexRoute
  '/chats/conversation': typeof AuthenticatedChatsConversationIndexRoute
  '/jobs/create': typeof AuthenticatedJobsCreateIndexRoute
  '/offers/create': typeof AuthenticatedOffersCreateIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/_home-layout': typeof AuthenticatedHomeLayoutRouteWithChildren
  '/_authenticated/_home-layout/account': typeof AuthenticatedHomeLayoutAccountRoute
  '/_authenticated/_home-layout/chats': typeof AuthenticatedHomeLayoutChatsRoute
  '/_authenticated/_home-layout/jobs': typeof AuthenticatedHomeLayoutJobsRoute
  '/_authenticated/_home-layout/offers': typeof AuthenticatedHomeLayoutOffersRoute
  '/_authenticated/_home-layout/': typeof AuthenticatedHomeLayoutIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/register/': typeof AuthRegisterIndexRoute
  '/_authenticated/chats/conversation/': typeof AuthenticatedChatsConversationIndexRoute
  '/_authenticated/jobs/create/': typeof AuthenticatedJobsCreateIndexRoute
  '/_authenticated/offers/create/': typeof AuthenticatedOffersCreateIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/account'
    | '/chats'
    | '/jobs'
    | '/offers'
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/chats/conversation'
    | '/jobs/create'
    | '/offers/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/account'
    | '/chats'
    | '/jobs'
    | '/offers'
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/chats/conversation'
    | '/jobs/create'
    | '/offers/create'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/_home-layout'
    | '/_authenticated/_home-layout/account'
    | '/_authenticated/_home-layout/chats'
    | '/_authenticated/_home-layout/jobs'
    | '/_authenticated/_home-layout/offers'
    | '/_authenticated/_home-layout/'
    | '/auth/login/'
    | '/auth/register/'
    | '/_authenticated/chats/conversation/'
    | '/_authenticated/jobs/create/'
    | '/_authenticated/offers/create/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/auth/login/",
        "/auth/register/"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/_home-layout",
        "/_authenticated/chats/conversation/",
        "/_authenticated/jobs/create/",
        "/_authenticated/offers/create/"
      ]
    },
    "/_authenticated/_home-layout": {
      "filePath": "_authenticated/_home-layout.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/_home-layout/account",
        "/_authenticated/_home-layout/chats",
        "/_authenticated/_home-layout/jobs",
        "/_authenticated/_home-layout/offers",
        "/_authenticated/_home-layout/"
      ]
    },
    "/_authenticated/_home-layout/account": {
      "filePath": "_authenticated/_home-layout/account.tsx",
      "parent": "/_authenticated/_home-layout"
    },
    "/_authenticated/_home-layout/chats": {
      "filePath": "_authenticated/_home-layout/chats.tsx",
      "parent": "/_authenticated/_home-layout"
    },
    "/_authenticated/_home-layout/jobs": {
      "filePath": "_authenticated/_home-layout/jobs.tsx",
      "parent": "/_authenticated/_home-layout"
    },
    "/_authenticated/_home-layout/offers": {
      "filePath": "_authenticated/_home-layout/offers.tsx",
      "parent": "/_authenticated/_home-layout"
    },
    "/_authenticated/_home-layout/": {
      "filePath": "_authenticated/_home-layout/index.tsx",
      "parent": "/_authenticated/_home-layout"
    },
    "/auth/login/": {
      "filePath": "auth/login/index.tsx"
    },
    "/auth/register/": {
      "filePath": "auth/register/index.tsx"
    },
    "/_authenticated/chats/conversation/": {
      "filePath": "_authenticated/chats/conversation/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/jobs/create/": {
      "filePath": "_authenticated/jobs/create/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/offers/create/": {
      "filePath": "_authenticated/offers/create/index.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
